security:
  password_hashers:
    App\Entity\Users: 'auto'
  enable_authenticator_manager: true
  providers:
    users:
      entity:
        class: App\Entity\Users
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      stateless: true
      provider: users
      json_login:
        check_path: login_check
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~

  access_control:
    - { path: ^/balance, roles: [ROLE_ADMIN, ROLE_USER] }
    - { path: ^/login, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10