#!/bin/sh

docker exec php ./vendor/bin/php-cs-fixer fix
if git diff; then
    echo "php-cs-fixer не онаружил проблем"
else
    echo "Внимание! php-cs-fixer нашел нарушения , код был исправлен! повторите commit"
    exit 1
fi

docker exec php ./vendor/bin/phpstan analyse
if [ $? -ne 0 ]; then
    echo "Внимание! phpstan обнаружил ошибки, необходимо исправить и закоммитить код заново"
    exit 1
else
    echo "phpstan не обнаружил ошибок"
fi

docker exec php ./vendor/bin/twig-cs-fixer lint --fix
if git diff; then
    echo "twig-cs-fixer не онаружил проблем"
else
    echo "Внимание! twig-cs-fixer нашел нарушения , код был исправлен! повторите commit"
    exit 1
fi

docker exec php ./vendor/bin/phpunit
if [ $? -eq 0 ]; then
    echo "тесты прошли успешно"
else
    echo "Внимание! Один или несколько тестов не прошли"
    exit 1
fi