<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240404000003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, voice UUID NOT NULL, users UUID NOT NULL, text VARCHAR(255) NOT NULL, full_price INT NOT NULL, format VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL)');
        $this->addSql('CREATE TABLE voices (id uuid NOT NULL DEFAULT uuid_generate_v4(), voice VARCHAR(255) NOT NULL, price INT NOT NULL, format VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E52FFDEEE7FB583B ON orders (voice)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E52FFDEE1483A5E9 ON orders (users)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEE7FB583B FOREIGN KEY (voice) REFERENCES voices (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE1483A5E9 FOREIGN KEY (users) REFERENCES users (guid) NOT DEFERRABLE INITIALLY IMMEDIATE');

    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE voices');
    }
}
