services:
  App\EventListener\ExceptionListener:
    tags: [ kernel.event_listener ]
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\AuthService:
    bind:
      $email: '%env(string:MAIL)%'
